### ISSUE TITLE
Always get this annoying error in my chrome dev tools when working on localhost

### ISSUE THREAD

**Issue by pavliha** [hanxue/transover#1]
```
Error in event handler for (unknown): SyntaxError: Unexpected end of JSON input
    at Object.TransOver.deserialize (chrome-extension://aggiiclaiamajehmlfpkjmlbadmkledi/lib/transover_utils.js:11:16)
    at chrome-extension://aggiiclaiamajehmlfpkjmlbadmkledi/contentscript.js:261:41
```

**Comment by w01fgang** [comment]
I also had this annoying error message, I've added localhost to "Don't translate words on these sites:" list and the error is gone.

**Comment by hanxue** [comment]
Sorry, this is a currently unmaintained fork. If this issue still occurs, please raise it at https://github.com/artemave/translate_onhover
